apiVersion: v1
kind: Service
metadata:
  name: my-nlb-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                       # use NLB
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"                 # internal scheme
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0abc1234def56789a"  # your subnet
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: my-app
