apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv-new
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName:    standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0863bab5cb2c07297   # change/update me
    fsType: xfs # previously was ext4

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
